#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Application.Resource", IsApplication=true)]

namespace Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int GeenAdministratie = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int Inloggen = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int Klant = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Leverancier = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int MeerToevoegen = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int OpslaanContacten1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int OpslaanContacten2 = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int Synchroniseer1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Synchroniseer2 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Synchroniseer3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Synchroniseer4 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int ToevoegenContacten1 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int ToevoegenContacten2 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int Verder = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int WacthwoordVergeten = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Administratie = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Gelukt = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Klant = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int KlantSnelstart = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int KlantTelefoon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Leverancier = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LeverancierSnelstart = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LeverancierTelefoon = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Selectie = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
