#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Application.Resource", IsApplication=true)]

namespace Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Borders = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mail_small = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int phone_small = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Snelstart = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int BelIcon1 = 2131034128;
			
			// aapt resource value: 0x7f050025
			public const int BelIcon2 = 2131034149;
			
			// aapt resource value: 0x7f050019
			public const int ContactenView = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int GeenAdministratie = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int GeluktText = 2131034120;
			
			// aapt resource value: 0x7f05003e
			public const int Inloggen = 2131034174;
			
			// aapt resource value: 0x7f050003
			public const int InvKoppelingkey = 2131034115;
			
			// aapt resource value: 0x7f05003f
			public const int KeuzeText = 2131034175;
			
			// aapt resource value: 0x7f050002
			public const int KiesAdministratieText = 2131034114;
			
			// aapt resource value: 0x7f050040
			public const int Klant = 2131034176;
			
			// aapt resource value: 0x7f050012
			public const int KlantInfo = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int KlantInfoView = 2131034131;
			
			// aapt resource value: 0x7f050021
			public const int KlantInfoView2 = 2131034145;
			
			// aapt resource value: 0x7f05000e
			public const int KlantNaam1 = 2131034126;
			
			// aapt resource value: 0x7f05001f
			public const int KlantNaam2 = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int KlantWoonplaats1 = 2131034129;
			
			// aapt resource value: 0x7f050020
			public const int KlantWoonplaats2 = 2131034144;
			
			// aapt resource value: 0x7f050027
			public const int LevInfo1 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int LevInfoView1 = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int LevInfoView3 = 2131034158;
			
			// aapt resource value: 0x7f050023
			public const int LevNaam = 2131034147;
			
			// aapt resource value: 0x7f050034
			public const int LevNaam3 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int LevPlaats3 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int LevView = 2131034166;
			
			// aapt resource value: 0x7f050026
			public const int LevWoonplaats1 = 2131034150;
			
			// aapt resource value: 0x7f050032
			public const int LevZoeken3 = 2131034162;
			
			// aapt resource value: 0x7f05002d
			public const int LevZoeken4 = 2131034157;
			
			// aapt resource value: 0x7f050033
			public const int Lev_Plaats3 = 2131034163;
			
			// aapt resource value: 0x7f050041
			public const int Leverancier = 2131034177;
			
			// aapt resource value: 0x7f050004
			public const int ListViewAdministratie = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int MailIcon1 = 2131034127;
			
			// aapt resource value: 0x7f050024
			public const int MailIcon2 = 2131034148;
			
			// aapt resource value: 0x7f050009
			public const int MeerToevoegen = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int Naam_Mail_Bel_Plaats = 2131034124;
			
			// aapt resource value: 0x7f05001e
			public const int Naam_Plaats = 2131034142;
			
			// aapt resource value: 0x7f050014
			public const int OpslaanContacten1 = 2131034132;
			
			// aapt resource value: 0x7f050029
			public const int OpslaanContacten2 = 2131034153;
			
			// aapt resource value: 0x7f05001c
			public const int SelecteerContacten1 = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int SelecteerContacten3 = 2131034135;
			
			// aapt resource value: 0x7f050031
			public const int SelecteerContacten4 = 2131034161;
			
			// aapt resource value: 0x7f05002c
			public const int SelecteerContacten5 = 2131034156;
			
			// aapt resource value: 0x7f050038
			public const int SnelstartLogo1 = 2131034168;
			
			// aapt resource value: 0x7f050000
			public const int SnelstartLogo2 = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int SnelstartLogo3 = 2131034122;
			
			// aapt resource value: 0x7f05001b
			public const int SnelstartLogo4 = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int SnelstartLogo6 = 2131034134;
			
			// aapt resource value: 0x7f050030
			public const int SnelstartLogo7 = 2131034160;
			
			// aapt resource value: 0x7f05002b
			public const int SnelstartLogo8 = 2131034155;
			
			// aapt resource value: 0x7f050007
			public const int SnelstartLogo9 = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int Synchroniseer1 = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int Synchroniseer2 = 2131034146;
			
			// aapt resource value: 0x7f05002f
			public const int Synchroniseer3 = 2131034159;
			
			// aapt resource value: 0x7f050037
			public const int Synchroniseer4 = 2131034167;
			
			// aapt resource value: 0x7f050015
			public const int ToevoegenContacten1 = 2131034133;
			
			// aapt resource value: 0x7f05002a
			public const int ToevoegenContacten2 = 2131034154;
			
			// aapt resource value: 0x7f050005
			public const int Verder = 2131034117;
			
			// aapt resource value: 0x7f05003d
			public const int WachtwoordVergeten = 2131034173;
			
			// aapt resource value: 0x7f050001
			public const int WelkomText = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int contactZoeken = 2131034136;
			
			// aapt resource value: 0x7f05003a
			public const int editTextEmail = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int editTextWachtwoord = 2131034172;
			
			// aapt resource value: 0x7f05000d
			public const int klantZoeken = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int klantZoeken1 = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int klantZoeken2 = 2131034141;
			
			// aapt resource value: 0x7f050039
			public const int textViewEmail = 2131034169;
			
			// aapt resource value: 0x7f05003b
			public const int textViewWachtwoord = 2131034171;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Administratie = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Gelukt = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Klant = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int KlantSnelstart = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int KlantTelefoon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Leverancier = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LeverancierSnelstart = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LeverancierTelefoon = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Selectie = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
